# Rakefile

require 'rake'

task default: ["build", "run"]

task :build do
  puts "Building..."
  source = Rake::FileList["**/*.c"].exclude("util.c", "stats.c")

  `clang util.c -Wall -Wextra -Wpedantic -c`
  `clang stats.c -Wall -Wextra -Wpedantic -c`

  source.each do |s|
    root = File.basename(s, ".*")
    `clang #{s} util.o stats.o -Wall -Wextra -Wpedantic -o #{root}`
  end

  print "\n----------------------------------------\n\n"
end

task :run do
  exec( "./c2" )
end

task test: ["build"]
task :test do
  exec( "./runner" )
end
